import type { Metadata } from 'next'
import './globals.css'

import localFont from 'next/font/local'
import Link from 'next/link'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ja'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className='min-h-screen flex flex-col'>
          <section className='py-4 shadow-md'>
            <header className='max-w-screen-lg mx-auto flex flex-row justify-between items-center'>
              <Link href='/'>
                <span className='text-4xl font-bold'>Todo-App</span>
              </Link>
              <nav>
                <ul className='flex flex-row gap-4'>
                  <li>
                    <Link
                      href='/'
                      className='px-8 py-4 bg-green-500 text-white rounded-full'
                    >
                      <span className='text-lg font-bold'>Todo登録</span>
                    </Link>
                  </li>
                </ul>
              </nav>
            </header>
          </section>
          <section className='max-w-screen-lg w-full mx-auto flex-1 p-4'>
            {children}
          </section>
          <section>
            <footer>
              <div className='bg-gray-800 text-white text-center py-4'>
                <span>© 2025 Todo-App</span>
              </div>
            </footer>
          </section>
        </div>
      </body>
    </html>
  )
}
